### ISSUE TITLE
MultipleSpouses not working on 1.6

### ISSUE THREAD

**Issue by Krono159** [aedenthorn/StardewValleyMods#142]
do you plan to update this mod for v1.6?

**Comment by FlyingTNT** [comment]
See [PolyamorySweet](https://www.nexusmods.com/stardewvalley/mods/20599).

**Comment by Krono159** [comment]
yep, it works, although i've started learning C# to fix this one myself lol

**Comment by FlyingTNT** [comment]
If you're going to fix it, you should know that prior to 1.6, MultipleSpouses was split into Free Love and a couple others, so you'd do best starting from there, because they should be closer to working.
