### ISSUE TITLE
MagnetMod optimization -or- question

### ISSUE THREAD

**Issue by sketchbook22** [aedenthorn/StardewValleyMods#34]
I suspect extra code is running.

Stardew Valley has code:
**Debris.updateChunks()**

Which it seems like your mod has modified slightly (to support your various features)
**ModEntry.UpdateTicking()**

If I'm reading this correctly, both methods would be running.  I would have thought this would be another Harmony Prefix.  

I am new to modding and suspect you have a reason that I am not aware of; and would like to learn your reason if you have time.  Thanks.

**Comment by aedenthorn** [comment]
the idea was to run the movement x - 1 times and let the updateChunks run the movement a final time. It's kind of ugly, but it does allow for a movement multiplier

**Comment by sketchbook22** [comment]
Understood, thank you for responding.
