### ISSUE TITLE
[Automate] Is it possible to connect the town and the beach?

### ISSUE THREAD

**Issue by ruanimal** [aedenthorn/StardewValleyMods#91]
I want to connect the town and the beach, put Crab Pot at the beach and connect it with "Wood Path". 
But it seems at the border of beach and the town, "wood path" can not put on it. 
how to solve it ?

**Comment by aedenthorn** [comment]
I didn't create the Automate mod

**Comment by ruanimal** [comment]
Sorry, I made a mistake about the repo.
